### ISSUE TITLE
Glossary and Information Sources

### ISSUE THREAD

**Issue by WJXHenry** [CMPUT301F19T22/3OwO1#19]
Project Tracking: #12 

Define any special terminology in the application domain (i.e., not programming terms). Provide a list of useful informational references or links to related or competitive products. Enter this information in your team wiki. Please clearly state the open source license for your project.

**Comment by WJXHenry** [comment]
@bojotamara is this task completed, or do we still need a list of references?

**Comment by bojotamara** [comment]
@WJXHenry It's completed, I'll move it to done
