### ISSUE TITLE
Add Firebase to Android Application

### ISSUE THREAD

**Issue by WJXHenry** [CMPUT301F19T22/3OwO1#46]
**Description:** 
Connect the Firebase project to the Android application

**Comment by WJXHenry** [comment]
**NOTE:** We should consider keeping the `google-services.json` file outside of the GitHub repo or, if possible, protect it since it contains our API key to Firestore. Not sure if this is really necessary for this project. Thoughts??

**Comment by bojotamara** [comment]
@WJXHenry I think we can keep it in, since this is the source code for the app. In a real life situation no one would have access to the source code.
